apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: YW1pdHJlY2hhdmlh # base64 encoded value of mongo-user
  mongo-password: VGhpc0lzTm90TXlQYXNzd29yZA== # base64 encoded value of mongo-password