apiVersion: apps/v1
kind: Deployment
metadata:
  name: topics-api
  labels:
    app: topics-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: topics-api
  template:
    metadata:
      name: topics-api
      labels:
        app: topics-api
    spec:
      containers:
        - name: topics-api
          image: maorel/topics-api:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: TOPICS_CORE_HOST
              valueFrom:
                configMapKeyRef:
                  key: core
                  name: services-config
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: mongo-url
                  name: mongo-config
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: mongo-user
                  name: mongo-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mongo-password
                  name: mongo-secret
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: topics-api-service
spec:
  selector:
    app: topics-api
  ports:
    - protocol: TCP
      port: 2345
      targetPort: 2345
      nodePort: 30001
  type: NodePort

